---
title: "Website Example"
---


```{r setup, include=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(vcd)
```

##  Introduction





## Results
#### 1. Does the number of COVID tests a student has taken in the 
so refuse H0 which means  the number of COVID tests a student has taken in the past two months does't follow a Poisson distribution. 
```{r,message=FALSE,warning=FALSE}
DATA2x02 <- read_csv("./DATA2x02 survey (Responses) - Form responses 1.csv")
DATA2x02 <-DATA2x02[which(!is.na(DATA2x02[,2])),]
COVID_tests_number = DATA2x02[which(!is.na(DATA2x02[,2])),2][[1]]
hist(COVID_tests_number, xlab="times",probability = TRUE,  main = "Arrivals from Aladdin Street")
lines(dpois(x=min(COVID_tests_number):max(COVID_tests_number), lambda=mean(COVID_tests_number)), col=2,lwd=3)
legend("topright", c("Probability of COVID tests in the past two months ", "Poisson Distribution Curve"),  fill=c(col=16, col=2))

gf <- goodfit(COVID_tests_number,type= "poisson")

plot(gf,main="Count data vs Poisson distribution")

```



## Appendix
The following References I used:

1. M. Friendly (2000), Visualizing Categorical Data. SAS Institute, Cary, NC.


